"use client";
import { useState } from "react";
import { ArrowRight, CheckCircle2, LockKeyhole } from "lucide-react";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

export default function LoginPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const supabase = createSupabaseBrowserClient();
  async function signIn() { if (!supabase) { setMessage("Supabase is not configured. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to enable live authentication."); return; } const { error } = await supabase.auth.signInWithPassword({ email, password }); setMessage(error?.message ?? "Signed in. Redirect to /dashboard to continue."); }
  async function google() { if (!supabase) { setMessage("Google OAuth becomes available after Supabase is configured."); return; } await supabase.auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/auth/callback` } }); }
  return <main className="login-page"><section className="login-visual"><div className="brand"><span className="brand-mark">M</span>MatriX</div><div className="login-visual-copy"><div className="eyebrow">Operations intelligence</div><h1>Move every project,<br />material and line<br />with confidence.</h1><p>One operational system for construction sites, warehouses and industrial production.</p></div><div className="login-foot"><span>Trusted operational data</span><span>•</span><span>Built for the field</span></div></section><section className="login-panel"><div className="login-card"><div className="mobile-brand"><div className="brand"><span className="brand-mark">M</span>MatriX</div></div><div className="eyebrow">Welcome back</div><h2>Sign in to your workspace</h2><p className="subtitle">Use your organization account to continue.</p><div className="login-form"><div className="field"><label htmlFor="email">Work email</label><input className="input" id="email" type="email" placeholder="you@company.com" value={email} onChange={(e) => setEmail(e.target.value)} /></div><div className="field"><label htmlFor="password">Password</label><input className="input" id="password" type="password" placeholder="Enter your password" value={password} onChange={(e) => setPassword(e.target.value)} /></div><button className="button primary login-button" onClick={signIn}>Sign in <ArrowRight size={15} /></button><button className="button google-button" onClick={google}>Continue with Google</button>{message && <div className="login-message"><LockKeyhole size={15} />{message}</div>}</div><div className="login-meta"><span><CheckCircle2 size={14} /> Secure Supabase Auth</span><a href="mailto:hello@matrix.app">Need access?</a></div></div></section></main>;
}
